@base = http://localhost:4000
@ts = {{$timestamp}}
  ///"email": "ada.1757532442@example.com",
### Login user
# @name login
POST {{base}}/api/v1/mongo/auth/login
Content-Type: application/json

{
  "email": "ada.1757532442@example.com",
  "password": "secret123"
}

###
@token = {{login.response.body.token}}

### Set productId to review
@productId = REPLACE_PRODUCT_ID
///productId = 68c12848883c8db19e2edcac

### Reviews: create
POST {{base}}/api/v1/mongo/reviews
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": "68c12848883c8db19e2edcac",
  "rating": 5,
  "comment": "Great product!"
}

### Reviews: by product
GET {{base}}/api/v1/mongo/reviews/product/{{productId}}

### Reviews: mine
GET {{base}}/api/v1/mongo/reviews/me
Authorization: Bearer {{token}}
